# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b156ede8c3d0daf98d71850552577f0228e0a289d2216714e11e07feb6ac837e8ad25bd9efdce9c4dbfe6772ac0c30ea26106d3ad2b72fd1e617b23e2268696c

test:
  secret_key_base: 9537000480ee1ff08f518d17d69a564dbc4743e1487bcc0927b8dbe501ea35f00ce8fb34902e0ec77cea4c92aa0c28698845ea881c1d8b1e82034e91c96f10b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
